CONTIKI = /home/tierex/opt/contiki/contiki-2.7

all: example-abc example-mesh example-collect example-trickle example-polite \
     example-rudolph0 example-rudolph1 example-rudolph2 example-rucb \
     example-runicast example-unicast example-neighbors

include /home/tierex/opt/contiki/contiki-2.7/Makefile.include
